# docker-compose.yml

services:

  bot:
    build: 
      context: .
      dockerfile: ./bot/Dockerfile
    expose:
      - "8001"
    volumes:
      - ./logs/bot:/app/logs
    networks:
      - reapbot_network
    env_file:
      - ./bot/.env


  flask-backend:
    build:
      context: .
      dockerfile: ./flask_app/Dockerfile
    expose:
      - "8000"
    volumes:
      - ./logs/flask:/app/logs
    env_file:
      - ./flask_app/.env
    networks:
      - reapbot_network
    environment:
      - FLASK_ENV=production


  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
      - ./nginx/certbot_nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx  # Mount the entire logs directory
    depends_on:
      - flask-backend

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
    depends_on:
      - nginx
  
  networks:
    reapbot_network:
      driver: bridge